name: "Display Hub Client"
description: "Client for HA Display Hub"
slug: "displayhub_client"
version: "0.1.0"
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
options:
  displayhub_host: "192.168.88.108"
  displayhub_port: 4510
  lcd_width: 16
  lcd_height: 2
  rotation_seconds: 5
  refresh_seconds: 2
  debug: false
  screens:
  - name: "Exterior"
    display: "rack1"
    entity: "sensor.alfa_clima_outside_temperature"
    decimals: 1
    progressbar: false
    scroll: true

  - name: "Cisterna"
    display: "rack2"
    entity: "sensor.nivel_cisterna"
    decimals: 0
    progressbar: true
    bar_style: "percent"
    bar_min: "0"
    bar_max: "100"
schema:
  displayhub_host: str
  displayhub_port: port
  lcd_width: int
  lcd_height: int
  rotation_seconds: int
  refresh_seconds: int
  debug: bool
  screens:
    - name: str
      display: str
      entity: str
      decimals: int?
      unit: str?
      progressbar: bool?
      bar_style: str?
      bar_min: str?
      bar_max: str?
      scroll: bool?
